### ISSUE TITLE
ReadMe Client

### ISSUE THREAD

**Issue by rbhowsden** [isFakeAccount/psnawp#1]
Just testing this out real quick, Client() would currently need request_builder passed to it...

`client = client.Client(psnawp.request_builder)`

**Comment by isFakeAccount** [comment]
I forgot to update the code in readme but if you do

`client = psnwp.Client()`

You don't need to pass anything. I'll fix it asap.

**Comment by isFakeAccount** [comment]
I fixed the issue in the recent commit d3c945f90a51e15ddea91292cadc54fe7333fedf

Thanks for letting me know.
