### ISSUE TITLE
Played Games by a User

### ISSUE THREAD

**Issue by jatinAffinidi** [isFakeAccount/psnawp#10]
I'm getting 
` requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://m.np.playstation.net/api/userProfile/v1/internal/users/6207657462640101457/basicPresences?type=primary`

this error on calling get_presence() function for particular account, can anyone help to find out what it mean and how can i solve this?

**Comment by isFakeAccount** [comment]
It could be because the user has made their profile private. I just tested the endpoint and the issue didn't occur for me.

**Comment by jatinAffinidi** [comment]
yeah it was private profile. Thank you very much
do we any end point which can give us which games are played by user?

**Comment by isFakeAccount** [comment]
I'll see what I can find. I'll add it along side with trophy endpoints

**Comment by isFakeAccount** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Games List](https://trello.com/c/qVU6N0ZE/2-add-games-list)

**Comment by isFakeAccount** [comment]
Issue fixed in release [1.1.0 ](https://github.com/isFakeAccount/psnawp/releases/tag/v1.1.0)
