### ISSUE TITLE
Trophy support?

### ISSUE THREAD

**Issue by Fried-man** [isFakeAccount/psnawp#11]
Currently here is nothing for seeing trophies a usr has and seeing the trophy list for specific games. The PHP library has it so it shouldn't be too difficult to implement here. If you want, I might be able to help :)

**Comment by ratbo99** [comment]
i added a funtion to the user.py and it works great. you can find a psn api v2 documentation here https://andshrew.github.io/PlayStation-Trophies/#/APIv2?id=obtaining-an-authentication-token

and here is my added function:
```
def getGameList(self, limit, offset):	
        response = self.request_builder.get(url='https://m.np.playstation.net/api/trophy/v1/users/me/trophyTitles?limit={}&offset={}'.format(limit, offset))
        #self.writeJSON(response,"gameList.json") 

        return response
```

**Comment by isFakeAccount** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Trophy Support](https://trello.com/c/n8wG9EtC/1-add-trophy-support)

**Comment by isFakeAccount** [comment]
Issue fixed in https://github.com/isFakeAccount/psnawp/releases/tag/v1.1.0
