### ISSUE TITLE
Get friends list of user

### ISSUE THREAD

**Issue by Lakrix** [isFakeAccount/psnawp#13]
Hey, is it possible to get a specific users friends by using their online/account Id?

**Comment by kerdion** [comment]
If you already know a user onlineId/accountId you can get that user directly:
`user = psnawp.user(online_id="VaultTec_Trading")`
If you need to fetch a user specifically from your friendlist I'd to this:

```
accountId = "111..." # your friend's accountId
friends = client.get_friends() # return a list of accountId
if accountId in friends:
    myFriend = psnawp.user(account_id=accountId)
```
