### ISSUE TITLE
Need assistance with a fan site that requires a Python PSN API wrapper

### ISSUE THREAD

**Issue by nemsoft** [isFakeAccount/psnawp#2]
Just wanted to reach out to you to ask if you wanted to contribute to a fan project that requires us to code a PSN API wrapper using Python - exactly like this project. If youre interested send me an email at bartekandre@gmail.com :)

**Comment by isFakeAccount** [comment]
I would say you should contact @pacMakaveli. I am not that good when it comes to reverse-engineering the endpoints from the PSN APK. As long as I know the endpoints I can program easily. 

Do you have a working python PSN API or perhaps know some endpoints? What is the status of the project overall?

**Comment by nemsoft** [comment]
Thanks for the quick reply :) The status is that we are are just starting with the PSN API and while doing research around it, I found this repo on Github and tought you might be a good match for our project. Are you familiar with this project: https://github.com/Tustin/psn-php ? It seems to do exactly what we require, but its in PHP so it would require some reverse engineering to Python.

**Comment by isFakeAccount** [comment]
PSN API is not really available for public use and all the endpoints that we got are from reverse-engineering the APK. You should check the APK file. Either download it from a website or extract it from your phone using ADB. 

There are a lot of apps available for decompiling apk. I am using JADAX GUI which I found [here](https://stackoverflow.com/questions/21010367/how-to-decompile-an-apk-or-dex-file-on-android-platform)
