### ISSUE TITLE
Why are python 3.7 and 3.8 no longer supported (1.0.0 and 1.0.1)?

### ISSUE THREAD

**Issue by HotGiardiniera** [isFakeAccount/psnawp#20]
Both python 3.7 and 3.8 are maintined and I am not seeing anything in the most recent release that is in 3.9 but not 3.8/7.

setup.py is requiring python >= 3.9 this is also happening in the 1.0.0 build

**Comment by isFakeAccount** [comment]
Python 3.8 might work. I didn't see a point in supporting 3.7 since it reached EOL. You have forked the repo. If you can pass the tests on python 3.8, I'll adjust the setup.cfg.

**Comment by isFakeAccount** [comment]
@HotGiardiniera 

I ditched python 3.8 and 3.7 mostly because of backward compatibility issues with typing module. I can see if I can support 3.8 by adding future imports. I doubt it will make it work on python 3.7.

**Comment by HotGiardiniera** [comment]
@isFakeAccount 3.8 would be great

**Comment by isFakeAccount** [comment]
@HotGiardiniera Looks like by adding `from __future__ import annotations` I can support python 3.8. I tried python 3.7 but the tests failed. 

Python 3.8+ tests: https://github.com/isFakeAccount/psnawp/actions/runs/3155030221

Python 3.7+ tests: https://github.com/isFakeAccount/psnawp/actions/runs/3154895794/jobs/5133011274

**Comment by isFakeAccount** [comment]
v1.0.2 support python 3.8.

**Comment by HotGiardiniera** [comment]
@isFakeAccount thanks a ton for the quick work 3.8 is great. Do you have a Paetron or anywhere I can send you some support cash?

**Comment by isFakeAccount** [comment]
I don't have a Paetron at the moment. Thanks for the offer.
