### ISSUE TITLE
why i can't get friend list, blocked list, available to play and groups

### ISSUE THREAD

**Issue by scachi27** [isFakeAccount/psnawp#21]
![psnawp](https://user-images.githubusercontent.com/99131319/194151963-67c1ceea-cb57-43d4-8087-19ab12ad6805.png)

why?

**Comment by isFakeAccount** [comment]
It is generator object. See the documentation. It has example code on how to use these.

https://psnawp.readthedocs.io/en/latest/psnawp_api.models.html#module-psnawp_api.models.client
