### ISSUE TITLE
get_group() function help

### ISSUE THREAD

**Issue by KhoyaDrillo** [isFakeAccount/psnawp#23]
![groups](https://user-images.githubusercontent.com/115801863/195864603-3d1fab92-0f22-45db-a1dc-e8618f2989e0.png)

how can i get the groups id?

**Comment by isFakeAccount** [comment]
Try `group.group_id`. It should autocomplete. Also, check the documentation.

 https://psnawp.readthedocs.io/en/latest/psnawp_api.models.html#module-psnawp_api.models.group

**Comment by KhoyaDrillo** [comment]
ok, i'll try it, thanks

**Comment by isFakeAccount** [comment]
Added repr and str in https://github.com/isFakeAccount/psnawp/releases/tag/v1.0.4
