### ISSUE TITLE
Can't find user via account_id

### ISSUE THREAD

**Issue by Flavestarr** [isFakeAccount/psnawp#3]
Hi there

Great API and I'm using it to get alerds when some of my friends go online.

After the recent changes, I'm not able to loop through my client.get_friends() over psnawp.user to get the user details.

It seems that the call psnawp.user() with parameter account_id isn't implemented correctly.

I guess the problem is in psnawp.py on line 40
```
        account_id = None
        if 'account_id' in kwargs.keys():
            online_id = kwargs['account_id']
```
Line 40 should be account_id = kwargs['account_id'] I guess.

Could you please take a look at this?

Regards
Flavestarr

**Comment by isFakeAccount** [comment]
Oops. I copy-pasted the code above and forgot to change all the values. Give me a moment and I'll fix it.

**Comment by isFakeAccount** [comment]
Fixed in https://github.com/isFakeAccount/psnawp/commit/ab46fea95991b4d6d2a0683bafc074193bc13a95
