### ISSUE TITLE
Authentication issue: 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by Lakrix** [isFakeAccount/psnawp#30]
Currently getting an error code when trying to authenticate.

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://ca.account.sony.com/api/authz/v3/oauth/authorize?access_type=offline&client_id=ac8d161a-d966-4728-b0ea-ffec22f69edc&scope=psn%3Aclientapp+psn%3Amobile.v1&redirect_uri=com.playstation.PlayStationApp%3A%2F%2Fredirect&response_type=code`

**Comment by HotGiardiniera** [comment]
Active thread related to this
https://github.com/Tustin/psn-php/issues/232

**Comment by isFakeAccount** [comment]
Ah. Man. Hopefully sony hasn't changed the auth. I'll look into it later.

**Comment by HotGiardiniera** [comment]
Looks like it is resolved via request parameter and authorization updates 
https://github.com/Tustin/psn-php/commit/88015f32e7cf19f666ecad80b23120f0f18ec1b4

**Comment by isFakeAccount** [comment]
Fixed in version [1.2.0](https://github.com/isFakeAccount/psnawp/releases/tag/v1.2.0)
