### ISSUE TITLE
NPSSO expiration date

### ISSUE THREAD

**Issue by radze90** [isFakeAccount/psnawp#35]
Hi,
is there a way to see how many days left the NPSSO is valid? Currently, only 3 days before the expiration is warned. I would like to check it manually.

thx 

EDIT:
When I read the following variable, I get back a json. Can I always read out the latest status or do I have to execute something first?
`psnawp._request_builder.authenticator._auth_properties
`
```
{'access_token': 'access_token...',
 'token_type': 'bearer',
 'expires_in': 3599,
 'scope': 'psn:mobile.v2.core psn:clientapp',
 'id_token': 'id_token...',
 'refresh_token': 'refresh_token...',
 'refresh_token_expires_in': 5183999,
 'access_token_expires_at': 1672657895.470685}
```

**Comment by isFakeAccount** [comment]
I'd recommend saving the values after you can created `psnawp` instance.

```py
    psnawp = PSNAWP(getenv('NPSSO_CODE'))
    refresh_token_expires_at = psnawp._request_builder.authenticator._auth_properties["refresh_token_expires_in"] + time.time()
```

You should be able to `use refresh_token_expires_at` to monitor the npsso expiration.

**Comment by radze90** [comment]
> ```python
>     refresh_token_expires_at = psnawp._request_builder.authenticator._auth_properties["refresh_token_expires_in"] + time.time()
> ```

Hello,

again a question about this. Why + time? Wouldn't that push the end time backwards and be wrong?

**Comment by isFakeAccount** [comment]
@radze90 No. I don't know where you get that it will push time backwards.
