### ISSUE TITLE
Query friends list of a user (besides the client)

### ISSUE THREAD

**Issue by Shinryin** [isFakeAccount/psnawp#42]
I have seen other APIs have this feature where you can get the friends list of a user using their PlayStation ID, etc.
I don't see the reciprocal function for this in the documents for this project in the users module, I would love for this to be added or pointed out to me if I missed it. Thank you.

**Comment by isFakeAccount** [comment]
I can look into it

**Comment by isFakeAccount** [comment]
I can't find a way to get the friends of friend on the mobile app. 

https://www.reddit.com/r/playstation/comments/k1c6zx/whats_wrong_with_the_new_ps_app_you_cant_view/

If you find a way to get the friends of friends in the app let me know. Then I can add this endpoint. 

@Shinryin

**Comment by Shinryin** [comment]
> I can't find a way to get the friends of friend on the mobile app.
> 
> https://www.reddit.com/r/playstation/comments/k1c6zx/whats_wrong_with_the_new_ps_app_you_cant_view/
> 
> If you find a way to get the friends of friends in the app let me know. Then I can add this endpoint.
> 
> @Shinryin

url = f"https://m.np.playstation.com/api/userProfile/v1/internal/users/{player_id}/friends"
headers = {
    "Authorization": f"Bearer {access_token}",
}

**Comment by isFakeAccount** [comment]
I guess that works. Thanks @Shinryin
