### ISSUE TITLE
Feature Request: Better auth / token refresh flow

### ISSUE THREAD

**Issue by Awmusic12635** [isFakeAccount/psnawp#5]
I know you are likely limited by what sony exposes to you but if it was possible to build in some kind of login / auth flow that would be really helpful. Additionally making it so tokens can be refreshed.

I was looking to use this in a python project of mine and I really can't be manually authing it all the time (even more so because I don't know how long this token lasts). 

Love the work on this so far!

**Comment by isFakeAccount** [comment]
Sony actually hasn't exposed anything to us. Most of the endpoints are reversed engineered from their the website or their app. 

Funny this is their website is also kinda broken. App works the best but it is pretty hard reading obfuscated code. 

The refresh token last for 2 months which should be good enough I think. I am not sure what you mean by manually authing all the time?

**Comment by Awmusic12635** [comment]
By manually authing I meant the process to have to manually go to the
website, login and then grab the token.

Is there a way to track the time remaining on the token?

**Comment by Flavestarr** [comment]
There was an earlier Project [mgp25/psn-api](https://github.com/mgp25/psn-api) which got the token automatically somehow... but it doesn't work anymore. I tried by myself to get the npsso token - without success.

Maybe there are some infos in the project you could use.

Anyway, for my usage the current solution is absolutely enough. Even if the token gets invalid, I just do the nessesary steps to auth again... takes me 1 minute max.

**Comment by isFakeAccount** [comment]
That method of authentication is discontinued by Sony. I don't know a way to get token from username and password as of now. I'll look into if later but no promises.

**Comment by isFakeAccount** [comment]
@Awmusic12635 yes see below. Also the bot will print a warning once your token is about to expire in 3 days. 

```
psnawp = psnawp.PSNAWP('<64 character npsso code>')   

print(psnawp.authenticator.refresh_token_expiration)
```

**Comment by isFakeAccount** [comment]
@Awmusic12635 I checked the authentication method and it appears that to prevent the bots from signing in. Sony uses this [Akamai Bot Manager Library](https://www.akamai.com/us/en/products/security/bot-manager.jsp). 

The library runs some sort of javascript code and generates a cookie and sends it to the server. The code is obfuscated obviously and it collects some sort of sensor data to make sure you are a human. The cookie is used later to return to npsso code which is then used for the remaining of the authentication. 

As of now, I could not find anything to defeat the library. Unfortunately. I might come back to this issue later at some point.
