### ISSUE TITLE
aboutMe doesn't work

### ISSUE THREAD

**Issue by Amethxst** [isFakeAccount/psnawp#50]
Trying to print aboutMe from any account will come up empty (even if it is not). I thought it was my error, but by checking several times and having "print(idonline.profile())" (where idonline = user input to write a psn id) print directly, the output for "aboutMe" is "'aboutMe': ''," i.e., blank, even though this is not. Only this currently seems not to work, the other keys (avatar, isPlus etc.. ) work perfectly

**Comment by isFakeAccount** [comment]
do you mean for `psnawp.user` or `psnawp.me`

About Me works for me for psnawp_user.

```py
user_example = psnawp.user(online_id="jeranther")
profile = user_example.profile()
print(profile)
```
Gives me 

![image](https://github.com/isFakeAccount/psnawp/assets/65515165/85c4f06a-209b-4ddb-99d8-c504d60783e9)

**Comment by Amethxst** [comment]
I checked now and it actually works, but I can assure you that for a couple of hours unfortunately it no longer printed the "bio".

![image](https://github.com/isFakeAccount/psnawp/assets/87199202/881a2b87-1f68-455d-ba8f-d800bdd432e2)

That was the output until yesterday. Now it works.

I'm sorry I possibly wasted your time

**Comment by isFakeAccount** [comment]
No worries
