### ISSUE TITLE
[Solved] Possible Issue with Authentication with PlayStation: Something went wrong while authenticating

### ISSUE THREAD

**Issue by isFakeAccount** [isFakeAccount/psnawp#53]
I am experiencing some issue with authentication. I am not sure it is only happening on my account. 

I'll look into it later. If you have same issue. Please comment below. 

```
Traceback (most recent call last):
  File "/root/Bots/GamerTagIDGrabber/main.py", line 211, in <module>                          psnawp = PSNAWP(os.getenv('NPSSO_CODE'))
  File "/root/Bots/GamerTagIDGrabber/venv/lib/python3.10/site-packages/psnawp_api/psnawp.py", line 39, in __init__
    self._request_builder = request_builder.RequestBuilder(authenticator.Authenticator(npsso_cookie))                                                                                 File "/root/Bots/GamerTagIDGrabber/venv/lib/python3.10/site-packages/psnawp_api/core/authenticator.py", line 34, in __init__                                                          self._authenticate()
  File "/root/Bots/GamerTagIDGrabber/venv/lib/python3.10/site-packages/psnawp_api/core/authenticator.py", line 120, in _authenticate
    raise psnawp_exceptions.PSNAWPAuthenticationError("Something went wrong while authenticating")
psnawp_api.core.psnawp_exceptions.PSNAWPAuthenticationError: Something went wrong while authenticating
```

**Comment by joalisonx** [comment]
Im having the same error here, its definitely not just your account. This is weird, today the PS3 got a new policy and now the API is possibly broken?  Maybe this policy has an effect on the API as well

**Comment by savandriy** [comment]
I've started having issues with accounts in the morning. Turned out Sony has rolled out a new TOS, and you need to log in and accept it, and get a fresh sso. Old sso tokens don't work.

**Comment by isFakeAccount** [comment]
> I've started having issues with accounts in the morning. Turned out Sony has rolled out a new TOS, and you need to log in and accept it, and get a fresh sso. Old sso tokens don't work.

Thanks. Looks like this solution works. I was worried that they changed Authentication Method.
