### ISSUE TITLE
N00b here 🖐️client.title_stats() Question

### ISSUE THREAD

**Issue by DomBartolo** [isFakeAccount/psnawp#57]
client.title_stats() returns a class object, and I've done a dir to check whats in it, but I can't seem to get any title stats from it. I'm looking for 'total number of hrs wasted on Elden Ring' type data, is that what this class can return?

**Comment by isFakeAccount** [comment]
Title Stats returns list of all the games you have played. You need to iterate over it. Something like

```py
client = psnawp.client()
for title_stat in client.title_stats()
   print(title_stat.name) # Print game name
   print(title_stat.play_duration) # How long you played this game. Uses timedelta object from datetime
```

Documentation:

- https://psnawp.readthedocs.io/en/latest/psnawp_api.models.html#psnawp_api.models.client.Client.title_stats
- https://psnawp.readthedocs.io/en/latest/psnawp_api.models.html#psnawp_api.models.title_stats.TitleStats

**Comment by DomBartolo** [comment]
Thanks, sorted it now. And thanks for putting this together generally!
