### ISSUE TITLE
Is there any way to use this and have access to the PSN Store and add or checkout avatars?

### ISSUE THREAD

**Issue by doumeem** [isFakeAccount/psnawp#62]
Sorry, for asking here if this is not the correct place to ask.

**Comment by isFakeAccount** [comment]
You can access user's avatars using profile method. 
As for the store? Theoretically yes, you can access it. But implementing it will be pita. What is your use case for accessing PlayStation Store via API?

**Comment by doumeem** [comment]
Sorry for the late response, just noticed you've answered me today.

I want to add items from the store, to user's cart, for example like avatars and etc, since there is no avatar shop in the PS5.

**Comment by isFakeAccount** [comment]
@doumeem It would be easier if you use the PlayStation App tbh.

**Comment by doumeem** [comment]
But there is no avatar in the PS App

**Comment by isFakeAccount** [comment]
@doumeem If it is not in app then I cannot implement it. All endpoints are taken from the app.
