### ISSUE TITLE
Is it possible to learn all of my PSN account nickname history?

### ISSUE THREAD

**Issue by Kamino16** [isFakeAccount/psnawp#65]
i changed many nicknames on my playstation account. i was wondering if there's a way for your code to show me all my old nicknames through the hex?? because it's always the same (would also be cool if i can see other's history)

**Comment by isFakeAccount** [comment]
I was actually looking for this functionality a while ago. But I don't think it is possible. This API wrapper can't do anything that your PSN App can't. 

If you find a way in the PSN App to do this then there might be a chance.
