### ISSUE TITLE
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by REFUZIION** [isFakeAccount/psnawp#67]
Whenever I try to initialize the psnawp package, I receive this error:

requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for URL: https://ca.account.sony.com/api/authz/v3/oauth/authorize

Stack trace:
```
Traceback (most recent call last):
  File "/Users/diede/Code/psn-id-api/main.py", line 22, in <module>
    app.psnawp = PSNAWP(npsso)
                 ^^^^^^^^^^^^^
  File "/Users/diede/Code/psn-id-api/.venv/lib/python3.12/site-packages/psnawp_api/psnawp.py", line 40, in __init__
    self._request_builder = request_builder.RequestBuilder(authenticator.Authenticator(npsso_cookie), accept_language, country)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diede/Code/psn-id-api/.venv/lib/python3.12/site-packages/psnawp_api/core/authenticator.py", line 34, in __init__
    self._authenticate()
  File "/Users/diede/Code/psn-id-api/.venv/lib/python3.12/site-packages/psnawp_api/core/authenticator.py", line 112, in _authenticate
    response.raise_for_status()
  File "/Users/diede/Code/psn-id-api/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://ca.account.sony.com/api/authz/v3/oauth/authorize?access_type=offline&client_id=123456789&scope=psn%3Amobile.v2.core+psn%3Aclientapp&redirect_uri=com.scee.psxandroid.scecompcall%3A%2F%2Fredirect&response_type=code
```

**Comment by isFakeAccount** [comment]
I am not able to reproduce this error. How are you using this? Also, make sure your npsso code is correct. 

`psnawp = PSNAWP(npsso)` only needs to be called once.

**Comment by REFUZIION** [comment]
It's a really weird issue, when I run the code local it gives me this error, however when I run it on my Linux server all is well. I tried running it over a proxy and a vpn as well but it threw the same error at me

**Comment by isFakeAccount** [comment]
@REFUZIION Try re-logging in and entering a new npsso code. Also, avoid re initialization of  class PSNAWP. Reuse the object if possible. 

In future update I'll add a way to save refresh token which might help as well.

**Comment by REFUZIION** [comment]
My code is a flask API that uses your package to retrieve the user by name. It initializes PSNAWP(npsso) on startup and saves it to the app variable. it doesn't get initialized more then once. I just tried to get a new npsso by logging in again and visiting the api/v1/ssocookie url. and it also returns `HTTP Status 429 – Too Many Requests` could that be the issue?

**Comment by REFUZIION** [comment]
Seems to have resolved itself. Maybe I got ratelimited by sony. Thanks for the help atleast!
