### ISSUE TITLE
No more get_title_id()

### ISSUE THREAD

**Issue by OsamaHeweitat** [isFakeAccount/psnawp#80]
The "[Implements GraphQL endpoint for the Search Class](https://github.com/isFakeAccount/psnawp/commit/c586e33ff63ee6bb69ed46581c2551f5fd073a32)" removed the `get_title_id()` functionality from search.

**Comment by isFakeAccount** [comment]
I removed `get_title_id()` for a few reasons. 

- The new endpoint doesn't return `title_id`
- The method wasn't anything special. It was just a wrapper around search method.
- It was sometimes misleading. Like it couldn't get PS3/PSVITA title ids because the search doesn't return any PS3/PSVITA titles. 

There are two ways of getting title id. 

1. https://andshrew.github.io/PlayStation-Titles
2. Using search like shown below

```py
from os import getenv

from dotenv import load_dotenv
from psnawp_api import PSNAWP
from psnawp_api.models import SearchDomain

load_dotenv()


def main() -> None:
    psn = PSNAWP(getenv("NPSSO_CODE", "NPSSO_CODE"))
    search = psn.search("Fallout 76", search_domain=SearchDomain.FULL_GAMES, limit=1)
    for result in search:
        print("Game Title Name", result["result"]["invariantName"])
        print("Content ID", result["result"]["defaultProduct"]["id"])


if __name__ == "__main__":
    main()
```

This will print

```bash
Game Title Name Fallout 76
Content ID UP1003-CUSA12057_00-PRJMTN0000000000
```

The title id here is `CUSA12057_00` which you can extract easily.

**Comment by OsamaHeweitat** [comment]
Thank you very much, this is a good replacement.

**Comment by isFakeAccount** [comment]
I am reopening this issue because in the documentation there still are references to `get_title_id`

**Comment by OsamaHeweitat** [comment]
> ```python
> defaultProduct
> ```

Is there a way to get the full Content ID (e.g. UP1003-CUSA12057_00-PRJMTN0000000000) without using search? such as using the trophy title? if not, is it something that would be possible to implement or is this a limitation of the API?

**Comment by isFakeAccount** [comment]
> Is there a way to get the full Content ID (e.g. UP1003-CUSA12057_00-PRJMTN0000000000) without using search? such as using the trophy title? if not, is it something that would be possible to implement or is this a limitation of the API?

@OsamaHeweitat trophyTitles endpoint does not return Title ID. Trophies use a different ID system which is called `npCommunicationId`. You really only need title id for one method. 

https://andshrew.github.io/PlayStation-Titles/ is probably the best way to find title ids besides the search endpoint.
