### ISSUE TITLE
{'code': 2122251, 'message': 'Ratelimit exceeded'} 

### ISSUE THREAD

**Issue by natrix5369** [isFakeAccount/psnawp#9]
Hey! Your authorization method has stopped working. Received token does not work. PSN server returns error: {'code': 2122251, 'message': 'Ratelimit exceeded'}

But if you use the authorization method through the browser, then everything is fine.

Can you solve this problem? Is there anything I can do to help?

**Comment by isFakeAccount** [comment]
Are you trying to get the messages or send messages? I noticed that the end pointed stopped working, perhaps Sony disabled it. I am gonna check if there are alternatives available but fingers crossed.

**Comment by natrix5369** [comment]
@isFakeAccount 
my project uses your module to get a token, as well as collect information about the user

On June 28, sony closes access to myPlayStation.com :(

I think we should try to see how the sony app for smartphone "communicates" with the servers. then we will find the API. but unfortunately I do not have a device for this :(

**Comment by isFakeAccount** [comment]
@natrix5369 read all the comments in the issue I mentioned.

**Comment by kerdion** [comment]
I managed to find the endpoints for messaging. Expect a PR in the next days/next week ❤️

**Comment by natrix5369** [comment]
> I managed to find the endpoints for messaging. Expect a PR in the next days/next week ❤️

You are the best! Can you tell me the details? I wonder how you did the analysis

**Comment by kerdion** [comment]
> > I managed to find the endpoints for messaging. Expect a PR in the next days/next week ❤️
> 
> You are the best! Can you tell me the details? I wonder how you did the analysis

I tried with reverse engineering the ps app, it took a whole day to understand the process but once inside the source code it was a mess of packages. Then I followed the comment section linked by isFakeAccount and with Httptoolkit and a lot of trial-error and googling I was able to bypass the ps app restriction and intercept the traffic

**Comment by natrix5369** [comment]
> > > I managed to find the endpoints for messaging. Expect a PR in the next days/next week ❤️
> > 
> > 
> > You are the best! Can you tell me the details? I wonder how you did the analysis
> 
> I tried with reverse engineering the ps app, it took a whole day to understand the process but once inside the source code it was a mess of packages. Then I followed the comment section linked by isFakeAccount and with Httptoolkit and a lot of trial-error and googling I was able to bypass the ps app restriction and intercept the traffic

I tried to run frida on android, but it didn't work :( PS the app just closed... but nevertheless thanks again for your efforts for the community!

**Comment by kerdion** [comment]
Yeah not going to lie it took a lot of effort, 3 days worths of trial and error (also I'm a rookie when it comes to networks and security, so...). 
Right now I'm working on the http requests and hopefully by next weekend I'll submit the PR so everyone can benefit from my hard work 😄

**Comment by natrix5369** [comment]
> Yeah not going to lie it took a lot of effort, 3 days worth of trial and error (also I'm a rookie when it comes to networks and security, so...). Right now I'm working on the http requests and hopefully by next weekend I'll submit the PR so everyone can benefit from my hard work 😄

how did you get the data? :)

it was also a great contribution!

unless of course it's too arrogant on my part)))

**Comment by isFakeAccount** [comment]
Get as many endpoints as you can. I can implement them.
