### ISSUE TITLE
Resource not found when trying to retrieve trophy list for PS5 games

### ISSUE THREAD

**Issue by antoniomsantos99** [isFakeAccount/psnawp#92]
Hello there!

When trying to retrieve the trophy list for a PS5 game like this:

`list(psnawp.game_title("PPSA01521_00").trophies("PS5"))`

The following error is raised:

`PSNAWPNotFound: {"error":{"referenceId":"55c4fee3-6d41-11ef-9bab-13e6a53004a3","code":2240525,"message":"Resource not found"}}`

The line of code works when retrieving trophies for PS4 game:

`list(psnawp.game_title("CUSA17676_00").trophies("PS4"))`

`[Trophy(trophy_set_version='01.06', has_trophy_groups=True, trophy_id=0, trophy_hidden=False, trophy_type=<TrophyType.PLATINUM: 'platinum'>, trophy_name='Platinum Golfer', trophy_detail='Collect all trophies', trophy_icon_url='https://image.api.playstation.com/trophy/np/NPWR19255_00_0079E137C5DC116E829FA1061EF3D2E6A83240E07E/5AB71F998427C5F9CBFF77AF63FAE2CD95A9804F.PNG', trophy_group_id='default', trophy_progress_target_value=None, trophy_reward_name=None, trophy_reward_img_url=None),
 (...)`

**Comment by isFakeAccount** [comment]
See this

https://github.com/isFakeAccount/psnawp/issues/72

You need to pass enum for PS5, not string.

**Comment by antoniomsantos99** [comment]
Yeah, that worked. I found it odd that for PS4 it worked.

Thank you very much!
