### ISSUE TITLE
How do I get npsso code by using the PSN email and password

### ISSUE THREAD

**Issue by shahriyardx** [isFakeAccount/psnawp#94]
It looks like the npsso expires after few hours, in such case how do I get new npsso without manually going to https://ca.account.sony.com/api/v1/ssocookie

**Comment by isFakeAccount** [comment]
npsso shouldn't expire for several months. Unless you are logging out or clearing browser cache from which you obtained npsso. 

Also, there is no way to get npsso from email and password. Otherwise it would have been part of the library already.
